// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfAD-JHB6_BY-wWjQdPFpj8DK6fFCm42c',
    appId: '1:1067204910332:web:07697602a6466f89964b79',
    messagingSenderId: '1067204910332',
    projectId: 'reading-record-e03a7',
    authDomain: 'reading-record-e03a7.firebaseapp.com',
    storageBucket: 'reading-record-e03a7.firebasestorage.app',
    measurementId: 'G-Y9WH9CQXVS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyIYphgk9mde1uIIK-TnSCLFml2C1USWc',
    appId: '1:1067204910332:android:17915e2c51a14061964b79',
    messagingSenderId: '1067204910332',
    projectId: 'reading-record-e03a7',
    storageBucket: 'reading-record-e03a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY2LNt8Edf5s9ZqFPCxxOAL3s2jNGlLOY',
    appId: '1:1067204910332:ios:159af4f64ef72317964b79',
    messagingSenderId: '1067204910332',
    projectId: 'reading-record-e03a7',
    storageBucket: 'reading-record-e03a7.firebasestorage.app',
    iosBundleId: 'com.hasangseon.readingRecordApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY2LNt8Edf5s9ZqFPCxxOAL3s2jNGlLOY',
    appId: '1:1067204910332:ios:159af4f64ef72317964b79',
    messagingSenderId: '1067204910332',
    projectId: 'reading-record-e03a7',
    storageBucket: 'reading-record-e03a7.firebasestorage.app',
    iosBundleId: 'com.hasangseon.readingRecordApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfAD-JHB6_BY-wWjQdPFpj8DK6fFCm42c',
    appId: '1:1067204910332:web:d4d4e5f1c1c94af1964b79',
    messagingSenderId: '1067204910332',
    projectId: 'reading-record-e03a7',
    authDomain: 'reading-record-e03a7.firebaseapp.com',
    storageBucket: 'reading-record-e03a7.firebasestorage.app',
    measurementId: 'G-3NPY4GPGE7',
  );
}
